### ISSUE TITLE
Reload button reboots device

### ISSUE THREAD

**Issue by theychx** [soreau/catt-qt#1]
The current behaviour of the reload button is counter-intuitive. I would expect for the content to be reloaded/restarted, not the device rebooting. Maybe you could have some sort of menu-button with auxilliary functionality, like reboot?

**Comment by soreau** [comment]
I had considered this but it was much easier to go with the existing flow and add a button. Patches welcome.

EDIT: In all fairness, I at least set the tooltip to "Reboot". :smile:

**Comment by soreau** [comment]
@theychx I agree there should be a refresh button too. One of my ideas is to use threading to load a splash screen or show an empty gui immediately, to be populated after discovery has completed, while waiting for the devices to be found. I haven't yet decided which widgets to use and what layout to put them in the gui, but there should be a way to reboot and refresh devices. What do you think the flow should look like?

**Comment by soreau** [comment]
@theychx I misread what you said about reloaded/restarted.. you can press enter in the text box and it will play the link, even if it is already casting. Or, you can click stop and then play. The refresh icon is for rebooting, and the tooltip says so too. There isn't really a better icon like a power-off icon I could find, [here is the list](https://joekuan.files.wordpress.com/2015/09/screen3.png) if you want to have a look. Ideas welcome.

Maybe we could have a button with text that says reboot and change the reboot button to restart current playback but it would only work for links in the text box. I'd rather not have the reload button reload because what do you if a tab is casting? disable the button or do nothing when it is clicked.. it would depend on whether there is something in the text box and then I have to hook up listeners for this.. too much. I figure users will quickly realize what the button does if they use it.

**Comment by theychx** [comment]
> you can press enter in the text box and it will play the link, even if it is already casting

That's kind of a silly way to restart content.
> The refresh icon is for rebooting, and the tooltip says so too

Even if you insist on this, another problem would be the placement of the button. This functionality does not belong together with transport buttons, where people might press it by mistake. And besides, how often do you need to reboot your chromecast? For me personally, I do it 2-3 times a year. As I've already stated, reboot should be hid away in some kind of menu.

As for reload/refresh, the oddly named `pychromecast.Chromecast.media_controller.rewind()` method actually restarts content, without you having to restart the cast dance.

**Comment by theychx** [comment]
> One of my ideas is to use threading to load a splash screen or show an empty gui immediately, to be populated after discovery has completed, while waiting for the devices to be found

Your current approach seems perfectly fine to me. Splash screen would also be cool. Empty gui sounds weird, some impatient users might think your code is broken.

**Comment by soreau** [comment]
>> you can press enter in the text box and it will play the link, even if it is already casting
> That's kind of a silly way to restart content.

I'd say it's expected behavior.

> another problem would be the placement of the [reboot] button .. reboot should be hid away in some kind of menu.

Maybe it can be like right-click-on-combobox-shows-reboot-option-as-single-entry-dropdown-list instead of a button. I agree the current placement and appearance isn't perfect, it's mainly to demo that rebooting actually works i.e. catt-qt detects the reboot and sets the initial volume. If this works, then it means that when the chromecast reboots itself and you go to play something, it isn't blasting at 100% volume the first time casting something after reboot.

> pychromecast.Chromecast.media_controller.rewind() method actually restarts content, without you having to restart the cast dance.

I can also seek to 0 for this, but rebooting functionality is not for this purpose.

**Comment by soreau** [comment]
> Splash screen would also be cool. Empty gui sounds weird, some impatient users might think your code is broken.

It would update the status text to inform the user it was waiting for devices to connect. On refresh button, I would expect it to rerun the discovery routine to search for devices it might not have found. At least on osx, discovery is unstable. It doesn't always find the devices. I blame the os in that case but, yea.

**Comment by soreau** [comment]
@theychx Thanks for your input, it now looks like [this](https://raw.githubusercontent.com/soreau/catt-qt/master/screenshot.png).
